baseURL = "https://jshakespeare.com/"
languageCode = "en"
title = "James Shakespeare"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[permalinks]
posts = "/:slug"
